name: 'Build Image'

on:
  push:
    branches: [ master, devel ]
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4.0.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v4.0.0

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v6.0.0
        with:
          images: Fellinger-Strema-Multi-Cash/piper
          labels: |
            org.opencontainers.image.title=piper
            org.opencontainers.image.version=0.0.0
            org.opencontainers.image.description=Piper CI Build

      - name: Build and Push Image
        uses: docker/build-push-action@v7.1.0
        env:
          SOURCE_DATE_EPOCH: 0
        with:
          context: .
          outputs: type=cacheonly
          cache-from: type=gha
          cache-to: type=gha
          #platforms: linux/amd64,linux/arm64
          platforms: linux/arm64
          push: false
          tags: Fellinger-Strema-Multi-Cash/piper
          labels: ci
          build-args: |
            PIPER_REPO_REF=main
